#!/usr/bin/env python3
"""Generate dist/BF2GameExt.ini from the C++ source of truth.

Reads:
  - PatcherDLL/src/util/ini_registry.hpp   (simple toggle entries)
  - PatcherDLL/src/controller/controller_support.cpp  (per-mode button defaults)

Writes:
  - dist/BF2GameExt.ini

Run from the repo root:  python generate_ini.py
"""

import re
import os
import sys
from collections import OrderedDict
from pathlib import Path

REPO = Path(__file__).resolve().parent
REGISTRY_HPP = REPO / "PatcherDLL" / "src" / "util" / "ini_registry.hpp"
CONTROLLER_CPP = REPO / "PatcherDLL" / "src" / "controller" / "controller_support.cpp"
OUTPUT_INI = REPO / "dist" / "BF2GameExt.ini"

# ── Parse ini_registry.hpp ──────────────────────────────────────────────

def parse_registry(path: Path):
    """Yield (section, key, default, comment) from INI_ENTRY / INI_PATCH lines."""
    text = path.read_text(encoding="utf-8")

    # Extract the block between BEGIN_REGISTRY and END_REGISTRY
    m = re.search(r"// BEGIN_REGISTRY\s*\n(.*?)// END_REGISTRY", text, re.DOTALL)
    if not m:
        sys.exit("ERROR: Could not find BEGIN_REGISTRY / END_REGISTRY in " + str(path))
    block = m.group(1)

    # Match INI_ENTRY("sec", "key", "def", "comment")
    # and   INI_PATCH("sec", "key", "def", "comment", "patch_name")
    pattern = re.compile(
        r'INI_(?:ENTRY|PATCH)\(\s*"([^"]*?)"\s*,\s*"([^"]*?)"\s*,\s*"([^"]*?)"\s*,\s*"([^"]*?)"'
    )
    for m in pattern.finditer(block):
        yield m.group(1), m.group(2), m.group(3), m.group(4)


# ── Parse controller_support.cpp for mode defaults ──────────────────────

def parse_controller_modes(path: Path):
    """Return OrderedDict  section_name -> [(input, actions), ...]"""
    text = path.read_text(encoding="utf-8")

    # Find s_modeSectionNames
    m = re.search(
        r's_modeSectionNames\s*\[.*?\]\s*=\s*\{(.*?)\};', text, re.DOTALL
    )
    if not m:
        sys.exit("ERROR: Could not find s_modeSectionNames in " + str(path))
    section_names = re.findall(r'"([^"]+)"', m.group(1))

    # Find each *Defaults[] array.  They appear in order matching s_modeDefaults.
    # s_modeDefaults lists them as: s_unitDefaults, s_vehicleDefaults, ...
    m = re.search(r's_modeDefaults\s*\[.*?\]\s*=\s*\{(.*?)\};', text, re.DOTALL)
    if not m:
        sys.exit("ERROR: Could not find s_modeDefaults in " + str(path))
    array_names = re.findall(r'(s_\w+Defaults)', m.group(1))

    if len(array_names) != len(section_names):
        sys.exit(
            f"ERROR: {len(array_names)} default arrays but {len(section_names)} section names"
        )

    modes = OrderedDict()
    for arr_name, sec_name in zip(array_names, section_names):
        pat = re.compile(
            rf'{re.escape(arr_name)}\s*\[\]\s*=\s*\{{(.*?)\{{\s*nullptr', re.DOTALL
        )
        am = pat.search(text)
        if not am:
            sys.exit(f"ERROR: Could not find array body for {arr_name}")
        body = am.group(1)
        bindings = re.findall(r'\{\s*"([^"]+)"\s*,\s*"([^"]*)"\s*\}', body)
        modes[sec_name] = bindings

    return modes


# ── Write INI ───────────────────────────────────────────────────────────

def write_ini(entries, modes, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)

    # Group entries by section, preserving order
    sections = OrderedDict()
    for section, key, default, comment in entries:
        sections.setdefault(section, []).append((key, default, comment))

    lines = []
    lines.append("; BF2GameExt.ini — auto-generated by generate_ini.py")
    lines.append("; Do not edit manually; update ini_registry.hpp or controller_support.cpp")
    lines.append("; and re-run:  python generate_ini.py")
    lines.append("")

    # Write simple sections from registry
    for section, keys in sections.items():
        lines.append(f"[{section}]")
        for key, default, comment in keys:
            if comment:
                lines.append(f"; {comment}")
            lines.append(f"{key}={default}")
        lines.append("")

    # Write controller binding sections
    lines.append("; Controller button/axis bindings per mode.")
    lines.append("; Keys are raw input names, values are comma-separated action names.")
    lines.append("; Omit a key or set it to empty to unbind.  Defaults are shown below.")
    lines.append("; See README.md for the full list of input and action names.")
    lines.append("")

    for sec_name, bindings in modes.items():
        lines.append(f"[{sec_name}]")
        for input_name, actions in bindings:
            if actions:
                lines.append(f";{input_name}={actions}")
            # Skip empty defaults (unbound by default)
        lines.append("")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\r\n")
    print(f"Generated {path}")


# ── Main ────────────────────────────────────────────────────────────────

def main():
    if not REGISTRY_HPP.exists():
        sys.exit(f"ERROR: {REGISTRY_HPP} not found (run from repo root)")
    if not CONTROLLER_CPP.exists():
        sys.exit(f"ERROR: {CONTROLLER_CPP} not found")

    entries = list(parse_registry(REGISTRY_HPP))
    modes = parse_controller_modes(CONTROLLER_CPP)
    write_ini(entries, modes, OUTPUT_INI)

    # Summary
    n_keys = len(entries) + sum(len(b) for b in modes.values())
    print(f"  {len(entries)} registry entries, {len(modes)} controller modes, {n_keys} total keys")


if __name__ == "__main__":
    main()
